global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'litellm'
    static_configs:
      - targets: ['litellm:4000']  # Assuming Litellm exposes metrics at port 4000

  - job_name: 'openmeter'
    static_configs:
      - targets: ['openmeter:8888']
    metrics_path: '/api/v1/debug/metrics'

  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8800']
    metrics_path: '/metrics'
